# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: monitoring

# Virtual machine IP
ip: 192.168.10.10

# Virtual machine CPU cores number
cpus: 2

# Virtual machine RAM
memory: 2048

# Virtal machine port for forwarding
port_virtual1: 3000
port_virtual2: 8086
# Host machine port for forwarding
port_host1: 3000
port_host2: 8086